--- 
title: "MIDFIELD Workshops"
author: "Richard Layton"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: MIDFIELDR/workshops
description: "A public site for workshops for access to MIDFIELD"
---


```{r include=FALSE}
# create a bib database for R packages
knitr::write_bib(
  c(.packages(), 'bookdown', 'knitr', 'rmarkdown')
  , 'packages.bib'
  )
```


# Preface {-}

This site provides access to workshop materials for studying how undergraduate students maneuver through their curricula using data from the MIDFIELD project [@2016ohlandlong] and the R [-@2018rcoreteam] and RStudio [-@2016rstudio] software environments for statistical computing and graphics. 

- **MIDFIELD** is the *Multiple-Institution Database for Investigating Engineering Longitudinal Development*---a student record database with approximately one million undergraduate students at sixteen US institutions from 1987 to 2016.  
- **midfieldr** is a R package that provides functions for turning raw MIDFIELD data into persistence metrics.  
- **midfielddata** is an R package  that provides a stratified sample of the MIDFIELD data: registrars' student records for 98,000 undergraduate students with proportional representation by institution, program, transfer status, sex, and race/ethnicity.  





